instagram_web/blueprints/users/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.user import *
from werkzeug.security import generate_password_hash

users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route('/new', methods=['GET'])
def new():
    return render_template('users/new.html')


@users_blueprint.route('/', methods=['POST'])
def create():
    
    user_password = request.form.get("password")
    user_hashed_password = generate_password_hash(user_password)
    
    new_user = User(username=request.form.get("username"), email=request.form.get("email"), password=user_hashed_password)


    if new_user.save():
        flash("Successfully signed up !", "success")
        return redirect(url_for('users.new'))
    else:
        return render_template('users/new.html', error=new_user.errors)


@users_blueprint.route('/<username>', methods=["GET"])
def show(username):
    pass


@users_blueprint.route('/', methods=["GET"])
def index():
    return "USERS"


@users_blueprint.route('/<id>/edit', methods=['GET'])
def edit(id):
    pass


@users_blueprint.route('/<id>', methods=['POST'])
def update(id):
    pass

instagram_web/blueprints/users/templates/users/new.html
 {% extends "_layout.html"%} {% block title %} Sign Up Page {% endblock%} {%
 block content %}

 {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} 

 {% for category, message in messages %}

 <div class="mt-3 alert alert-{{ category }}">{{ message }}</div>

 {% endfor %} {% endif %} {% endwith %}

 {% for errors in error if error|length > 0 %}

     <div class="mt-3 alert alert-danger">{{ errors }}</div>    

 {% endfor %}

 <div class="m-3">
   <h1>Sign Up</h1>
 </div>

 <form class="mx-3" action="{{ url_for('users.create') }}" method="POST">
   <div class="form-group">
     <label for="exampleInputEmail1">Username</label>
     <input
       type="text"
       class="form-control"
       id="exampleInputEmail1"
       aria-describedby="emailHelp"
       placeholder="Enter username"
       name="username"
     />
   </div>
   <div class="form-group">
     <label for="exampleInputEmail1">Email address</label>
     <input
       type="email"
       class="form-control"
       id="exampleInputEmail1"
       aria-describedby="emailHelp"
       placeholder="Enter email"
       name="email"
     />
     <small id="emailHelp" class="form-text text-muted"
       >We'll never share your email with anyone else.</small
     >
   </div>
   <div class="form-group">
     <label for="exampleInputPassword1">Password</label>
     <input
       type="password"
       class="form-control"
       id="exampleInputPassword1"
       placeholder="Password"
       name="password"
     />
   </div>
   <div class="form-group">
     <label for="exampleInputPassword1">Confirm Password</label>
     <input
       type="password"
       class="form-control"
       id="exampleInputPassword1"
       placeholder="Password"
     />
   </div>
   <button type="submit" class="btn btn-primary">Submit</button>
 </form>

 {% endblock %}